# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "starter"
client_id = "e1c7b16b940d2ee8a973ccc03f2b95d4"
application_url = "https://teen-slightly-considered-bachelor.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://teen-slightly-considered-bachelor.trycloudflare.com/auth/callback",
  "https://teen-slightly-considered-bachelor.trycloudflare.com/auth/shopify/callback",
  "https://teen-slightly-considered-bachelor.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2021-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "leme-nl.myshopify.com"
